version: "3.7"
services:
  mysql-image:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - ${SERVER_PORT:-8081}:3306
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - .app.env
